<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE specialConfigs [
  <!ELEMENT specialConfigs (configuration*) >
  <!ELEMENT configuration (name, frontEnd, frequency, sideband, mixers, mode, systems, bandwidth, shift+) >
  <!ELEMENT name (#PCDATA) >
  <!ELEMENT frontEnd (#PCDATA) >
  <!ELEMENT frequency (#PCDATA) >
  <!ELEMENT sideband (#PCDATA) >
  <!ELEMENT mixers (#PCDATA) >
  <!ELEMENT mode (#PCDATA) >
  <!ELEMENT systems (#PCDATA) >
  <!ELEMENT bandwidth (#PCDATA)>
  <!ELEMENT shift (#PCDATA)>
]>


<specialConfigs>
<configuration>
  <name>      NS_H2CO_125X2   </name>
  <frontEnd>  A3              </frontEnd>
  <frequency> 218.34890       </frequency>
  <sideband>  LSB             </sideband>
  <mixers>    1               </mixers>
  <mode>      DSB             </mode>
  <systems>   2               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     0.12625         </shift>
  <shift>     -0.12625        </shift>
</configuration>

<configuration>
  <name>      NS_H2CO_125X4   </name>
  <frontEnd>  A3              </frontEnd>
  <frequency> 218.49113       </frequency>
  <sideband>  LSB             </sideband>
  <mixers>    1               </mixers>
  <mode>      DSB             </mode>
  <systems>   4               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     -0.26875         </shift>
  <shift>     -0.015           </shift>
  <shift>     0.26875          </shift>
  <shift>     -0.26875         </shift>
</configuration>

<configuration>
  <name>      NS_13C18O_125X2 </name>
  <frontEnd>  A3              </frontEnd>
  <frequency> 219.9795        </frequency>
  <sideband>  USB             </sideband>
  <mixers>    1               </mixers>
  <mode>      DSB             </mode>
  <systems>   2               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     0.41875          </shift>
  <shift>     -0.41875         </shift>
</configuration>

<configuration>
  <name>      NS_SOC18O_125X2 </name>
  <frontEnd>  A3              </frontEnd>
  <frequency> 219.7549        </frequency>
  <sideband>  USB             </sideband>
  <mixers>    1               </mixers>
  <mode>      DSB             </mode>
  <systems>   2               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     0.1945          </shift>
  <shift>     -0.1945         </shift>
</configuration>

<configuration>
  <name>      NS_COHCN_125AB  </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 354.17575       </frequency>
  <sideband>  USB             </sideband>
  <mixers>    2               </mixers>
  <mode>      DSB             </mode>
  <systems>   1               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     0.355          </shift>
</configuration>

<configuration>
  <name>      NS_COHCN_125_A  </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 354.17575       </frequency>
  <sideband>  USB             </sideband>
  <mixers>    1               </mixers>
  <mode>      DSB             </mode>
  <systems>   2               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     0.355          </shift>
</configuration>

<configuration>
  <name>      NS_COHCN_125_B  </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 354.17575       </frequency>
  <sideband>  USB             </sideband>
  <mixers>    1               </mixers>
  <mode>      DSB             </mode>
  <systems>   1               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     0.355          </shift>
</configuration>

<configuration>
  <name>      NS_COHCN_250AB  </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 354.20075       </frequency>
  <sideband>  USB             </sideband>
  <mixers>    2               </mixers>
  <mode>      DSB             </mode>
  <systems>   1               </systems>
  <bandwidth> 250.0           </bandwidth>
  <shift>     0.355          </shift>
</configuration>

<configuration>
  <name>      NS_COHCN_250_A  </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 354.20075       </frequency>
  <sideband>  USB             </sideband>
  <mixers>    1               </mixers>
  <mode>      DSB             </mode>
  <systems>   1               </systems>
  <bandwidth> 250.0           </bandwidth>
  <shift>     0.355          </shift>
</configuration>

<configuration>
  <name>      NS_COHCN_250_B  </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 354.20075       </frequency>
  <sideband>  USB             </sideband>
  <mixers>    1               </mixers>
  <mode>      DSB             </mode>
  <systems>   1               </systems>
  <bandwidth> 250.0           </bandwidth>
  <shift>     0.355          </shift>
</configuration>

<configuration>
  <name>      NS_HCNHNC_250AB </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 362.61790       </frequency>
  <sideband>  USB             </sideband>
  <mixers>    2               </mixers>
  <mode>      DSB             </mode>
  <systems>   1               </systems>
  <bandwidth> 250.0           </bandwidth>
  <shift>     0.0625          </shift>
</configuration>

<configuration>
  <name>      NS_HCNHNC_250_A </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 362.61790       </frequency>
  <sideband>  USB             </sideband>
  <mixers>    1               </mixers>
  <mode>      DSB             </mode>
  <systems>   1               </systems>
  <bandwidth> 250.0           </bandwidth>
  <shift>     0.0625          </shift>
</configuration>

<configuration>
  <name>      NS_HCNHNC_250_B </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 362.61790       </frequency>
  <sideband>  USB             </sideband>
  <mixers>    1               </mixers>
  <mode>      DSB             </mode>
  <systems>   1               </systems>
  <bandwidth> 250.0           </bandwidth>
  <shift>     0.0625          </shift>
</configuration>

<configuration>
  <name>      NS_HCNDCN_125AB </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 362.30100       </frequency>
  <sideband>  USB             </sideband>
  <mixers>    2               </mixers>
  <mode>      DSB             </mode>
  <systems>   1               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     -0.23         </shift>
</configuration>

<configuration>
  <name>      NS_HCNDCN_125_A </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 362.30100       </frequency>
  <sideband>  USB             </sideband>
  <mixers>    1               </mixers>
  <mode>      DSB             </mode>
  <systems>   1               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     -0.23         </shift>
</configuration>

<configuration>
  <name>      NS_HCNDCN_125_B </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 362.30100       </frequency>
  <sideband>  USB             </sideband>
  <mixers>    1               </mixers>
  <mode>      DSB             </mode>
  <systems>   1               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     -0.23         </shift>
</configuration>

<configuration>
  <name>      NS_COH13CN_125A </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 345.56790       </frequency>
  <sideband>  LSB             </sideband>
  <mixers>    1               </mixers>
  <mode>      SSB             </mode>
  <systems>   2               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     -0.2275         </shift>
  <shift>     0.2275          </shift>
</configuration>

<configuration>
  <name>      NS_COH13CN_125B </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 345.56790       </frequency>
  <sideband>  LSB             </sideband>
  <mixers>    1               </mixers>
  <mode>      SSB             </mode>
  <systems>   2               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     -0.2275         </shift>
  <shift>     0.2275          </shift>
</configuration>

<configuration>
  <name>      NS_H2DN2H_125AB </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 372.54690       </frequency>
  <sideband>  USB             </sideband>
  <mixers>    2               </mixers>
  <mode>      SSB             </mode>
  <systems>   4               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     -0.125         </shift>
  <shift>     0.125          </shift>  
  <shift>     -0.125         </shift>
  <shift>     0.125          </shift>  
</configuration>

<configuration>
  <name>      NS_H2DN2H_125A  </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 372.54690       </frequency>
  <sideband>  USB             </sideband>
  <mixers>    1               </mixers>
  <mode>      SSB             </mode>
  <systems>   2               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     -0.125         </shift>
  <shift>     0.125          </shift>  
</configuration>

<configuration>
  <name>      NS_H2DN2H_125B  </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 372.54690       </frequency>
  <sideband>  USB             </sideband>
  <mixers>    1               </mixers>
  <mode>      SSB             </mode>
  <systems>   2               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     -0.125         </shift>
  <shift>     0.125          </shift>  
</configuration>

<configuration>
  <name>      NS_CNCN_125AB  </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 340.1398        </frequency>
  <sideband>  USB             </sideband>
  <mixers>    2               </mixers>
  <mode>      SSB             </mode>
  <systems>   4               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     -0.1075         </shift>
  <shift>     0.1075          </shift>  
  <shift>     -0.1075         </shift>
  <shift>     0.1075          </shift>  
</configuration>

<configuration>
  <name>      NS_COPCOP_125AB  </name>
  <frontEnd>  B3              </frontEnd>
  <frequency> 353.8778        </frequency>
  <sideband>  LSB             </sideband>
  <mixers>    2               </mixers>
  <mode>      SSB             </mode>
  <systems>   4               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     -0.13625         </shift>
  <shift>     0.13625          </shift>  
  <shift>     -0.13625         </shift>
  <shift>     0.13625          </shift>  
</configuration>

<configuration>
  <name>      NS_SIOSO_125x2  </name>
  <frontEnd>  A3              </frontEnd>
  <frequency> 261.18085       </frequency>
  <sideband>  USB             </sideband>
  <mixers>    1               </mixers>
  <mode>      SSB             </mode>
  <systems>   2               </systems>
  <bandwidth> 125.0           </bandwidth>
  <shift>     -0.2025         </shift>
  <shift>     0.2025          </shift>  
</configuration>

</specialConfigs>

